<?php
/**
 * @file
 * Extreme display tweaking.
 *
 * @copyright Copyright(c) 2013 Christopher Skene
 * @license GPL v2 http://www.fsf.org/licensing/licenses/gpl.html
 * @author Chris Skene chris at xtfer dot com
 */

/**
 * Implements hook_menu_alter().
 */
function term_hider_menu_alter(&$items) {
  $items['taxonomy/term/%taxonomy_term']['page callback'] = 'term_hider_term_page';
  $items['taxonomy/term/%taxonomy_term']['file'] = '';
}

/**
 * Menu callback; displays all nodes associated with a term.
 *
 * @param object $term
 *   The taxonomy term.
 *
 * @return string
 *   The page content.
 */
function term_hider_term_page($term) {
  // Assign the term name as the page title.
  drupal_set_title($term->name);

  // Build breadcrumb based on the hierarchy of the term.
  $current = (object) array(
    'tid' => $term->tid,
  );

  // @todo This overrides any other possible breadcrumb and is a pure hard-coded
  //   presumption. Make this behavior configurable per vocabulary or term.
  $breadcrumb = array();

  // Add terms to breadcrumb.
  while ($parents = taxonomy_get_parents($current->tid)) {
    $current = array_shift($parents);
    $breadcrumb[] = l($current->name, 'taxonomy/term/' . $current->tid);
  }

  // Add vocab to breadcrumb.
  $vocabulary = taxonomy_vocabulary_load($term->vid);
  $breadcrumb[] = $vocabulary->name;

  // Home.
  $breadcrumb[] = l(t('Home'), NULL);
  $breadcrumb = array_reverse($breadcrumb);
  drupal_set_breadcrumb($breadcrumb);

  // drupal_add_feed('taxonomy/term/' . $term->tid . '/feed', 'RSS - ' . $term->name);

  // If there is a menu link to this term, the link becomes the last part of
  // the active trail, and the link name becomes the page title. Thus, we must
  // explicitly set the page title to be the node title.
  $uri = entity_uri('taxonomy_term', $term);

  // Set the term path as the canonical URL to prevent duplicate content.
  drupal_add_html_head_link(array(
    'rel' => 'canonical',
    'href' => url($uri['path'], $uri['options'])),
    TRUE
  );
  // Set the non-aliased path as a default shortlink.
  drupal_add_html_head_link(array(
    'rel' => 'shortlink',
    'href' => url($uri['path'], array_merge($uri['options'], array('alias' => TRUE))),
  ), TRUE);

  $build = taxonomy_term_show($term);

  return $build;
}
